# Generated by Django 4.1.7 on 2023-03-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, default='/static/images/no_image.png', null=True, upload_to='uploads/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='account',
            name='user_info',
            field=models.TextField(max_length=512, null=True, verbose_name='Информация о пользователе'),
        ),
    ]
