# Generated by Django 4.1.7 on 2023-03-27 07:20

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, default='/static/images/no_image.png', null=True, upload_to='avatars', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(max_length=11, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(11), accounts.models.validate_digits], verbose_name='Номер телефона'),
        ),
    ]
