# Generated by Django 4.1.7 on 2023-04-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_avatar_alter_account_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/no_image.png', null=True, upload_to='avatars', verbose_name='Аватар'),
        ),
    ]
